on:
  workflow_call:
    inputs:
      client-id:
        type: string
        description: OAuth client ID (sometimes called consumer key) of the connected app on Salesforce used to connect to the Dev Hub org
        required: false
        default: 3H7cm0QedwevwtVKpSJ4PXeI7kvPanBgB3qK0sBU06E5MSMka3xqeg9JETRkx8Z8PQxuZkUvlMJH10MQ8A9uw
      jwt-key-file:
        type: string
        description: Path to an Ansible Vault-encrypted file containing the private key to connect to the Dev Hub org with using the JWT flow
        required: true
    secrets:
      ansible-vault-password:
        description: Password to be used to decrypt the `jwt-key-file`.
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SALESFORCE_CONSUMER_ID: 3H7cm0QedwevwtVKpSJ4PXeI7kvPanBgB3qK0sBU06E5MSMka3xqeg9JETRkx8Z8PQxuZkUvlMJH10MQ8A9uw

    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: install jq
        run: sudo apt-get install -y jq

      - name: set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: install Salesforce CLI (sfdx)
        run: npm list -g sfdx-cli || npm install -g sfdx-cli

      - name: write Ansible Vault password to file
        run: echo "${{ secrets.VAULT_PASSWORD }}" >.vault-password

      - name: decrypt the private key for the Continuous Integration connected app
        run: ansible-vault decrypt --vault-password-file=.vault-password deploy/environments/prod/wtax--prod.key

      - name: connect to Dev Hub
        run: |
          sfdx auth:jwt:grant \
              -i "${{ env.SALESFORCE_CONSUMER_ID }}" \
              -f deploy/environments/prod/wtax--prod.key \
              -r https://login.salesforce.com \
              -u admin@wtax.co -d

      - name: create scratch org
        run: sfdx force:org:create -d 1 -s -f config/project-scratch-def.json

      - name: install texei plugin
        run: echo y | sfdx plugins:install texei-sfdx-plugin

      - name: install dependencies
        run: sfdx texei:package:dependencies:install -w 15 -r

      - name: push sources to scratch org
        run: sfdx force:source:push -f

      - name: run unit tests
        run: sfdx force:apex:test:run -l RunLocalTests -y

      - name: package the source as metadata
        run: ./build.sh target/${{ github.event.repository.name }}-${{ github.sha }}.zip

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/${{ github.event.repository.name }}-${{ github.sha }}.zip

      - name: delete scratch org
        run: sfdx force:org:delete -p
        if: always()
