on:
  workflow_call:
    inputs:
      source-directory:
        type: string
        description: Directory containing the main source of the project. Usually force-app, but can be something else. API versions will only be bumped in this directory.
        required: false
        default: force-app
      api-version:
        type: string
        description: A Salesforce API version in the majorVersion.minorVersion format, e.g. 61.0
        required: true
      jira-issue:
        type: string
        description: A Jira issue number to include in the commit message
        required: true
jobs:
  bump-api-version:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: bump API versions
        run: find . -name '*-meta.xml' -exec sed -i 's/<apiVersion>\([^<]*\)<\/apiVersion>/<apiVersion>${{ inputs.api-version }}<\/apiVersion>/' '{}' \;
        working-directory: ${{ inputs.source-directory }}

      - name: commit changes
        run: |
            git config --global user.name '${{ github.actor }}'
            git config --global user.email '${{ github.actor }}@users.noreply.github.com'
            git commit -am "${{ inputs.jira-issue }} Bumped API versions to ${{ inputs.api-version }}"
            git push